Algoritmo "semnome"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/11/2019
Var
// Seção de Declarações das variáveis
 v: vetor [1..30] de inteiro
 i: inteiro
 dobro: real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
para i de 1 ate 30 faca
dobro <- i^2
escreva (dobro )
fimpara

Fimalgoritmo