Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/11/2019
Var
// Seção de Declarações das variáveis 
v: vetor [1..3] de inteiro
i: inteiro
numero : real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para i de 1 ate 3 faca
escreval ("Escreva o ", i ,"° numero: ")
leia  (v[i])
fimpara
escreval (v [1])
escreval (v [3])

Fimalgoritmo