Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/11/2019
Var
// Seção de Declarações das variáveis 
v: vetor [1..10]de  real
i: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para i de 1 ate 10 faca
escreva ("Informe o número ", i, ": ")
leia(v[i])
fimpara

para i de 10 ate 1 passo -1 faca
escreva (v[i])
fimpara


Fimalgoritmo